status: 1
pattern: '[node:field_reference_type]: [node:field_person]'
escape: false
preserve_titles: false
save: false
chunk: 50
dependencies:
  config:
    - node.type.person_reference
new_content_behavior: 0
