status: 1
pattern: '[node:field_contact_type]: [node:field_street_and_number], [node:field_place]'
escape: false
preserve_titles: false
save: false
chunk: 50
dependencies:
  config:
    - node.type.contact_information
new_content_behavior: 0
