status: 1
pattern: '[node:field_published_edition:entity:title] - [node:field_published_edition:entity:field_scope]'
escape: false
preserve_titles: false
save: false
chunk: 50
dependencies:
  config:
    - node.type.published_edition_reference
new_content_behavior: 1
