status: 1
pattern: '[node:field_source_term:entity:name]'
escape: false
preserve_titles: false
save: false
chunk: 50
dependencies:
  config:
    - node.type.digital_localization
new_content_behavior: 0
