_core:
  default_config_hash: zDwqaWPY76K_8TgX6aS789W7nZIEg7lU9MJsoh61bAU
minimum_single: 20
minimum_multiple: 0
disable_search_threshold: 0
minimum_width: 0
max_shown_results: null
use_relative_width: false
jquery_selector: 'select:visible'
search_contains: false
disable_search: false
allow_single_deselect: false
allow_mobile: false
add_helper_buttons: false
disabled_themes:
  olivero: '0'
  claro: '0'
  bartik: '0'
  islandora_muni: '0'
chosen_include: 2
placeholder_text_multiple: Select
placeholder_text_single: Select
no_results_text: 'No results match'
