cloneable_entities:
  - block
  - block_content
  - block_content_type
  - citation_select_csl_style
  - comment_type
  - comment
  - contact_message
  - contact_form
  - context
  - editor
  - facets_facet_source
  - facets_facet
  - facets_summary
  - field_config
  - field_storage_config
  - file
  - filter_format
  - group
  - group_config_wrapper
  - group_role
  - group_relationship
  - group_type
  - group_relationship_type
  - image_style
  - key_config_override
  - key
  - configurable_language
  - language_content_settings
  - media
  - media_type
  - menu_link_content
  - migration
  - migration_group
  - node_type
  - node
  - path_alias
  - rdf_mapping
  - responsive_image_style
  - rest_resource_config
  - search_api_task
  - search_api_server
  - search_api_index
  - solr_cache
  - solr_field_type
  - solr_request_dispatcher
  - solr_request_handler
  - shortcut_set
  - shortcut
  - simple_block
  - action
  - menu
  - taxonomy_vocabulary
  - taxonomy_term
  - tour
  - user
  - user_role
  - pathauto_pattern
  - view
  - entity_form_display
  - entity_form_mode
  - entity_view_display
  - entity_view_mode
  - date_format
  - base_field_override
  - config_split
